import os

AWS_COGNITO_REGION = os.getenv("AWS_COGNITO_REGION")
AWS_COGNITO_USER_POOL_ID = os.getenv("AWS_COGNITO_USER_POOL_ID")
AWS_COGNITO_CLIENT_ID = os.getenv("AWS_COGNITO_CLIENT_ID")
AWS_S3_BUCKET_NAME = os.getenv("AWS_S3_BUCKET_NAME")
