/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:59e3eb92-b1aa-4442-bece-0a20836aec74",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_xWi4rGQV8",
    "aws_user_pools_web_client_id": "1p9ln7l2b6s1551f5t1obdh2i6",
    "oauth": {
        "domain": "eu-west-1xwi4rgqv8.auth.eu-west-1.amazoncognito.com",
        "scope": [
            'openid'
        ],
        "redirectSignIn": "http://localhost:3000/homepage",
        "redirectSignOut": "http://localhost:3000",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS", "EMAIL"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": "8",
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ]
};


export default awsmobile;
